package view;

public class MenuView extends javax.swing.JFrame {
   data mostra_data;
    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
        mostra_data = new data();
        mostra_data.le_data();
    //    label_data.setText(mostra_data.dia_semana+
    //            ", "+mostra_data.dia+" de "+mostra_data.mes+
   //             " de "+mostra_data.ano);
        mostra_data.le_hora();
   //     label_hora.setText(mostra_data.hora);        
        timer1.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
   /* public void ValidaTipoUsuario() {
        if (){
        
         jMenuItemControleAcesso.setEnabled(true);
         jMenuItemGrupo.setEnabled(true);
         jMenuItemUsuario.setEnabled(true);
         
        } else {              
         jMenuItemControleAcesso.setEnabled(false);
         jMenuItemGrupo.setEnabled(false);
         jMenuItemUsuario.setEnabled(false);
         }
    }
    * */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        popupMenu1 = new java.awt.PopupMenu();
        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        jToolBar4 = new javax.swing.JToolBar();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_Cadastros = new javax.swing.JMenu();
        jMenuItemControles1 = new javax.swing.JMenu();
        jMenuItemGrupo = new javax.swing.JMenuItem();
        jMenuItemUsuario = new javax.swing.JMenuItem();
        jMenuItemEspecificos = new javax.swing.JMenu();
        menuitem_corretor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuSair = new javax.swing.JMenu();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        popupMenu1.setLabel("popupMenu1");

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Ficha");
        setPreferredSize(new java.awt.Dimension(1261, 642));
        setResizable(false);

        jToolBar4.setBorder(null);
        jToolBar4.setFloatable(false);
        jToolBar4.setRollover(true);
        jToolBar4.setEnabled(false);
        jToolBar4.setRequestFocusEnabled(false);
        jToolBar4.setVerifyInputWhenFocusTarget(false);

        menu_Cadastros.setText("Cadastros");

        jMenuItemControles1.setText("Controles");

        jMenuItemGrupo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemGrupo.setText("Grupo de Usuários");
        jMenuItemGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGrupoActionPerformed(evt);
            }
        });
        jMenuItemControles1.add(jMenuItemGrupo);

        jMenuItemUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemUsuario.setText("Usuários");
        jMenuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioActionPerformed(evt);
            }
        });
        jMenuItemControles1.add(jMenuItemUsuario);

        menu_Cadastros.add(jMenuItemControles1);

        jMenuItemEspecificos.setText("Específicos");
        jMenuItemEspecificos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEspecificosActionPerformed(evt);
            }
        });

        menuitem_corretor.setText("Ficha");
        menuitem_corretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuitem_corretorActionPerformed(evt);
            }
        });
        jMenuItemEspecificos.add(menuitem_corretor);

        menu_Cadastros.add(jMenuItemEspecificos);
        menu_Cadastros.add(jSeparator1);

        jMenuBar1.add(menu_Cadastros);

        jMenuSair.setText("Sair");
        jMenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSairMouseClicked(evt);
            }
        });
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1074, 1074, 1074))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(746, 746, 746))
        );

        setSize(new java.awt.Dimension(471, 319));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGrupoActionPerformed
        new GrupoView().setVisible(true);
    }//GEN-LAST:event_jMenuItemGrupoActionPerformed

    private void jMenuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioActionPerformed
        new UsuarioView().setVisible(true);
    }//GEN-LAST:event_jMenuItemUsuarioActionPerformed

    private void jMenuItemEspecificosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEspecificosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemEspecificosActionPerformed

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        mostra_data.le_hora();
     //  label_hora.setText(mostra_data.hora);
    }//GEN-LAST:event_timer1OnTime

    private void jMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSairActionPerformed
        
    }//GEN-LAST:event_jMenuSairActionPerformed

    private void jMenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSairMouseClicked
        new FecharSIstemaView().setVisible(true);
    }//GEN-LAST:event_jMenuSairMouseClicked

    private void menuitem_corretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitem_corretorActionPerformed
           new FichaVIEW().setVisible(true);
    }//GEN-LAST:event_menuitem_corretorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuItemControles1;
    private javax.swing.JMenu jMenuItemEspecificos;
    private javax.swing.JMenuItem jMenuItemGrupo;
    private javax.swing.JMenuItem jMenuItemUsuario;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar4;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JMenu menu_Cadastros;
    private javax.swing.JMenuItem menuitem_corretor;
    private java.awt.PopupMenu popupMenu1;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables
}
